### ISSUE TITLE
Could you please provide the environment for PPO training?

### ISSUE THREAD

**Issue by SunHaoOne** [JeffTheHacker/ContingenciesFromObservations#5]
Thank you for providing source code of your brilliant work on vehicle trajectory prediction. I have finished training and testing your models both on your method and MFP method. And I am really interested in the reinforcement learning for training, so can you please provide your enviroment for PPO training? Thanks a lot.

**Comment by cpacker** [comment]
Hi @SunHaoOne, thanks for your interest in our work!

For the PPO baseline, what we did was:
- reproduce a version of the left turn environment in the Oatomobile repository (https://github.com/OATML/oatomobile), which uses the OpenAI Gym API
  - basically, set up spawn points for an ego vehicle and actor vehicle with the hardcoded coordinates here: https://github.com/JeffTheHacker/ContingenciesFromObservations/blob/main/Experiment/Left_Turn_Scenario/scenario_specifics.py
  - generate a reference plan for the ego vehicle using the CARLA global planner from the ego spawn to ego goal (the ego then only controls acceleration along this path, since it seems too difficult for PPO to control all of brake/steer/throttle)
  - make the actor responsive with a hard-coded policy that's triggered each time `env.step` is called, you can just use the policy defined in: https://github.com/JeffTheHacker/ContingenciesFromObservations/blob/main/Experiment/Left_Turn_Scenario/behaviors.py
- train PPO on the new gym environment using Stable Baselines (https://stable-baselines.readthedocs.io/en/master/)

Note that we only did this for the left turn scenario. When I have time I can attempt to clean the code to push a fork of each repo, but in the meantime if you would like to try implementing a version of it yourself (e.g., with the latest version of oatomobile) I can also try to answer any further questions.
